#!/bin/bash
# Compiles Claudio in release and assembles Claudio.app (in /Applications by default).
#
# Usage:
#   Scripts/build_app.sh              local build (certificate "Plume Local Dev")
#   NOTARIZE=1 Scripts/build_app.sh   shareable build: Developer ID + hardened
#                                     runtime + Apple notarization + zip in dist/
#
# Environment variables:
#   SIGN_IDENTITY    local identity (default: "Plume Local Dev", the historical
#                    name of the self-signed certificate in the Keychain;
#                    independent of the app's name, keeping it avoids recreating
#                    a certificate)
#   DEV_ID_IDENTITY  Developer ID identity (default: auto-detected in the Keychain)
#   NOTARY_PROFILE   notarytool profile (default: "claudio-notary")
#   DEST             install folder (default: /Applications)
#
# Notarization prerequisites, one time only (Apple Developer account required):
#   1. Certificate: Xcode → Settings… → Accounts → Manage Certificates… →
#      + → "Developer ID Application".
#   2. Credentials: an app password at https://account.apple.com, then
#      xcrun notarytool store-credentials claudio-notary \
#        --apple-id <apple-id> --team-id <TEAMID> --password <app-password>
#      (the TEAMID is in parentheses in the certificate's name)
#
# ⚠️ Without a stable certificate, the ad hoc signature changes on every build
# and macOS re-prompts for Accessibility + Keychain access after each rebuild.
set -euo pipefail
cd "$(dirname "$0")/.."

APP_NAME="Claudio"
BUNDLE_ID="com.guillaumedhios.claudio"
VERSION="1.9.0"
SIGN_IDENTITY="${SIGN_IDENTITY:-Plume Local Dev}"
NOTARY_PROFILE="${NOTARY_PROFILE:-claudio-notary}"
DEST="${DEST:-/Applications}"
APP="$DEST/$APP_NAME.app"

echo "→ Resolving dependencies…"
swift package resolve

# Dependency fix, to reapply on every build (SPM checkouts aren't versioned).
# The resource access generated by SwiftPM looks for the KeyboardShortcuts
# bundle at the root of the .app; codesign refuses to seal anything there, so
# the bundle lives in Contents/Resources and the access fails with a
# fatalError as soon as the Shortcuts tab opens. On the build machine the
# fallback to .build hides the crash: it only showed up for users.
KS_UTILS=".build/checkouts/KeyboardShortcuts/Sources/KeyboardShortcuts/Utilities.swift"
KS_FIX='Bundle.main.resourceURL.flatMap { Bundle(url: $0.appendingPathComponent("KeyboardShortcuts_KeyboardShortcuts.bundle")) } ?? .main'
if [ -f "$KS_UTILS" ]; then
    if grep -q 'bundle: \.module' "$KS_UTILS"; then
        echo "→ KeyboardShortcuts fix (resource bundle path)…"
        sed -i '' "s|bundle: \\.module|bundle: $KS_FIX|" "$KS_UTILS"
    fi
    if ! grep -q "KeyboardShortcuts_KeyboardShortcuts.bundle" "$KS_UTILS"; then
        echo "❌ KeyboardShortcuts fix not applied: the dependency has changed."
        echo "   Check $KS_UTILS before publishing, otherwise the Shortcuts tab will crash."
        exit 1
    fi
else
    echo "❌ KeyboardShortcuts dependency not found in .build/checkouts."
    exit 1
fi

echo "→ Compiling (release)…"
swift build -c release

echo "→ Assembling $APP…"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp ".build/release/$APP_NAME" "$APP/Contents/MacOS/$APP_NAME"

# SPM resource bundles (KeyboardShortcuts' Bundle.module fatalErrors without them).
for bundle in .build/release/*.bundle; do
    [ -e "$bundle" ] && cp -R "$bundle" "$APP/Contents/Resources/"
done

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key><string>fr</string>
	<key>CFBundleExecutable</key><string>$APP_NAME</string>
	<key>CFBundleIdentifier</key><string>$BUNDLE_ID</string>
	<key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
	<key>CFBundleName</key><string>$APP_NAME</string>
	<key>CFBundlePackageType</key><string>APPL</string>
	<key>CFBundleShortVersionString</key><string>$VERSION</string>
	<key>CFBundleVersion</key><string>1</string>
	<key>LSMinimumSystemVersion</key><string>14.0</string>
	<key>LSUIElement</key><true/>
	<key>NSHighResolutionCapable</key><true/>
	<key>NSHumanReadableCopyright</key><string>© Guillaume Dhios</string>
</dict>
</plist>
PLIST

# Optional icon: drop an AppIcon.icns in icon/ to embed it.
if [ -f "icon/AppIcon.icns" ]; then
    cp "icon/AppIcon.icns" "$APP/Contents/Resources/AppIcon.icns"
    /usr/libexec/PlistBuddy -c "Add :CFBundleIconFile string AppIcon" "$APP/Contents/Info.plist"
fi

xattr -cr "$APP" 2>/dev/null || true

if [ "${NOTARIZE:-0}" = "1" ]; then
    echo "→ Developer ID signature (hardened runtime)…"
    if [ -z "${DEV_ID_IDENTITY:-}" ]; then
        DEV_ID_IDENTITY=$(security find-identity -v -p codesigning \
            | sed -n 's/.*"\(Developer ID Application: [^"]*\)".*/\1/p' | head -1)
    fi
    if [ -z "$DEV_ID_IDENTITY" ]; then
        echo "❌ No \"Developer ID Application\" certificate in the Keychain."
        echo "   Create it once: Xcode → Settings… → Accounts →"
        echo "   Manage Certificates… → + → \"Developer ID Application\"."
        exit 1
    fi
    echo "   Identity: $DEV_ID_IDENTITY"
    codesign --force --sign "$DEV_ID_IDENTITY" --options runtime --timestamp "$APP"
    codesign --verify --strict "$APP"

    echo "→ Apple notarization (a few minutes)…"
    mkdir -p dist
    UPLOAD_ZIP="dist/.upload.zip"
    rm -f "$UPLOAD_ZIP"
    ditto -c -k --keepParent "$APP" "$UPLOAD_ZIP"
    if ! SUBMIT_OUT=$(xcrun notarytool submit "$UPLOAD_ZIP" \
            --keychain-profile "$NOTARY_PROFILE" --wait 2>&1); then
        echo "$SUBMIT_OUT"
        echo "❌ Submission failed. If the \"$NOTARY_PROFILE\" profile doesn't exist,"
        echo "   create it once (app password on account.apple.com):"
        echo "   xcrun notarytool store-credentials $NOTARY_PROFILE \\"
        echo "     --apple-id <apple-id> --team-id <TEAMID> --password <app-password>"
        rm -f "$UPLOAD_ZIP"
        exit 1
    fi
    echo "$SUBMIT_OUT"
    rm -f "$UPLOAD_ZIP"
    if ! echo "$SUBMIT_OUT" | grep -q "status: Accepted"; then
        SUBMISSION_ID=$(echo "$SUBMIT_OUT" | sed -n 's/^ *id: //p' | head -1)
        echo "❌ Notarization rejected. Report details:"
        echo "   xcrun notarytool log $SUBMISSION_ID --keychain-profile $NOTARY_PROFILE"
        exit 1
    fi

    echo "→ Stapling the ticket…"
    xcrun stapler staple "$APP"

    SHARE_ZIP="dist/$APP_NAME-$VERSION.zip"
    rm -f "$SHARE_ZIP"
    ditto -c -k --keepParent "$APP" "$SHARE_ZIP"
    echo "✅ $SHARE_ZIP ready to share (unzip into /Applications, double-click)."
else
    echo "→ Local signature…"
    # Direct attempt: a self-signed certificate works even flagged
    # CSSMERR_TP_NOT_TRUSTED (which `find-identity -v` wouldn't list).
    if codesign --force --sign "$SIGN_IDENTITY" "$APP" 2>/dev/null; then
        echo "   Signed with \"$SIGN_IDENTITY\"."
    else
        echo "⚠️  Certificate \"$SIGN_IDENTITY\" not found → ad hoc signature."
        echo "    macOS will re-prompt for Accessibility/Keychain after each rebuild."
        echo "    To create the certificate (once): Keychain Access →"
        echo "    Certificate Assistant → Create a Certificate… →"
        echo "    name \"$SIGN_IDENTITY\", type \"Code Signing\", self-signed root."
        codesign --force --sign - "$APP"
    fi
    codesign --verify --strict "$APP"
fi

touch "$APP"
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f "$APP" >/dev/null 2>&1 || true

echo "✅ $APP ready. Launch with: open \"$APP\""
